method: TF_RFF

data:
  n_views_train: 10
  n_lights_per_view_train: 30
  n_lights_per_view_test: 20
  n_train_views_for_metrics: 100  # Number of views to use to compute metrics during traing

model:
  # EXTRINSIC - RFF
  feature_strategy: rff
  # NOTE: in_dim = 510 * 2 (sin, cos) + 3 (include_input) = 1023
  embed_include_input: True
  k: 512
  embed_std: 8
  num_layers: 6
  mlp_hidden_dim: 128
  skip_layer_idx: 3
  batchnorm: False

dataloader:
  batch_size_exp: 14

training:
  loss_type: L1     # Can be L1 or MSE
  learning_rate: 0.0001
  num_epochs: 100

logging:
  rendering_interval: 50

optimizer:
  lr_sched_type: exp
  lr_sched_gamma: 0.9

timing:
  batch_size_exp: 15
  repetitions: 400

seed: 0