  mesh_views_list_train:
    - human023
    - human010
    - human013
    - human004
    - human012

  mesh_views_list_val:
    - human_val000
    - human_val001
    - human_val002
    - human_val003
    - human_val004
    - human_val005
    - human_val006
    - human_val007
    - human_val008
    - human_val009
    - human_val010
    - human_val011
    - human_val012
    - human_val013
    - human_val014
    - human_val015
    - human_val016
    - human_val017
    - human_val018
    - human_val019
    - human_val020
    - human_val021
    - human_val022
    - human_val023
    - human_val024
    - human_val025
    - human_val026
    - human_val027
    - human_val028
    - human_val029
    - human_val030
    - human_val031
    - human_val032
    - human_val033
    - human_val034
    - human_val035
    - human_val036
    - human_val037
    - human_val038
    - human_val039
    - human_val040
    - human_val041
    - human_val042
    - human_val043
    - human_val044
    - human_val045
    - human_val046
    - human_val047
    - human_val048
    - human_val049
    - human_val050
    - human_val051
    - human_val052
    - human_val053
    - human_val054
    - human_val055
    - human_val056
    - human_val057
    - human_val058
    - human_val059
    - human_val060
    - human_val061
    - human_val062
    - human_val063
    - human_val064
    - human_val065
    - human_val066
    - human_val067
    - human_val068
    - human_val069
    - human_val070
    - human_val071
    - human_val072
    - human_val073
    - human_val074
    - human_val075
    - human_val076
    - human_val077
    - human_val078
    - human_val079
    - human_val080
    - human_val081
    - human_val082
    - human_val083
    - human_val084
    - human_val085
    - human_val086
    - human_val087
    - human_val088
    - human_val089
    - human_val090
    - human_val091
    - human_val092
    - human_val093
    - human_val094
    - human_val095
    - human_val096
    - human_val097
    - human_val098
    - human_val099

  # Images which are completely rendered after the evaluation step (not part of the training dataset)
  mesh_views_list_test:
    # - human023
    - human_test000
    - human_test001
    - human_test002
    - human_test003
    - human_test004
    - human_test005
    - human_test006
    - human_test007
    - human_test008
    - human_test009
    - human_test010
    - human_test011
    - human_test012
    - human_test013
    - human_test014
    - human_test015
    - human_test016
    - human_test017
    - human_test018
    - human_test019
    - human_test020
    - human_test021
    - human_test022
    - human_test023
    - human_test024
    - human_test025
    - human_test026
    - human_test027
    - human_test028
    - human_test029
    - human_test030
    - human_test031
    - human_test032
    - human_test033
    - human_test034
    - human_test035
    - human_test036
    - human_test037
    - human_test038
    - human_test039
    - human_test040
    - human_test041
    - human_test042
    - human_test043
    - human_test044
    - human_test045
    - human_test046
    - human_test047
    - human_test048
    - human_test049
    - human_test050
    - human_test051
    - human_test052
    - human_test053
    - human_test054
    - human_test055
    - human_test056
    - human_test057
    - human_test058
    - human_test059
    - human_test060
    - human_test061
    - human_test062
    - human_test063
    - human_test064
    - human_test065
    - human_test066
    - human_test067
    - human_test068
    - human_test069
    - human_test070
    - human_test071
    - human_test072
    - human_test073
    - human_test074
    - human_test075
    - human_test076
    - human_test077
    - human_test078
    - human_test079
    - human_test080
    - human_test081
    - human_test082
    - human_test083
    - human_test084
    - human_test085
    - human_test086
    - human_test087
    - human_test088
    - human_test089
    - human_test090
    - human_test091
    - human_test092
    - human_test093
    - human_test094
    - human_test095
    - human_test096
    - human_test097
    - human_test098
    - human_test099
    - human_test100
    - human_test101
    - human_test102
    - human_test103
    - human_test104
    - human_test105
    - human_test106
    - human_test107
    - human_test108
    - human_test109
    - human_test110
    - human_test111
    - human_test112
    - human_test113
    - human_test114
    - human_test115
    - human_test116
    - human_test117
    - human_test118
    - human_test119
    - human_test120
    - human_test121
    - human_test122
    - human_test123
    - human_test124
    - human_test125
    - human_test126
    - human_test127
    - human_test128
    - human_test129
    - human_test130
    - human_test131
    - human_test132
    - human_test133
    - human_test134
    - human_test135
    - human_test136
    - human_test137
    - human_test138
    - human_test139
    - human_test140
    - human_test141
    - human_test142
    - human_test143
    - human_test144
    - human_test145
    - human_test146
    - human_test147
    - human_test148
    - human_test149
    - human_test150
    - human_test151
    - human_test152
    - human_test153
    - human_test154
    - human_test155
    - human_test156
    - human_test157
    - human_test158
    - human_test159
    - human_test160
    - human_test161
    - human_test162
    - human_test163
    - human_test164
    - human_test165
    - human_test166
    - human_test167
    - human_test168
    - human_test169
    - human_test170
    - human_test171
    - human_test172
    - human_test173
    - human_test174
    - human_test175
    - human_test176
    - human_test177
    - human_test178
    - human_test179
    - human_test180
    - human_test181
    - human_test182
    - human_test183
    - human_test184
    - human_test185
    - human_test186
    - human_test187
    - human_test188
    - human_test189
    - human_test190
    - human_test191
    - human_test192
    - human_test193
    - human_test194
    - human_test195
    - human_test196
    - human_test197
    - human_test198
    - human_test199
