seed: 0
method: neutex
experiment:
  name: Default Neutex
  split: other_method/neutex/human/default
  description: Default Config for human using neutex method
data:
  raw_data_path: data/raw/human_dataset_v2_tiny/
  preproc_data_path: data/preprocessed/human_dataset_v2_tiny/
  eigenfunctions_path: data/preprocessed/human_efuncs/eigenfunctions_cotan_kmax4096_skip_first_efuncs.npy
  mesh_path: data/raw/human/RUST_3d_Low1.obj
  img_height: 512
  img_width: 512
  data_split: config/texture/human/data_split.yaml
  train_render_img_names:
    - human_vis000
    - human000
    - human_val000
    - human_test000

  render_img_directory: results_texture/
model:
  type: neutex
  feature_strategy: xyz
  pretrained_path: src/other_methods/neutex/pretrained/human_pretrained_neutex_mapping.pt
  # Linspace with embedding size for positional encoding => 170 * 2 * 3 + 3 = 1023
  k: 170
  use_logspace: False
  max_freq: 6
training:
  out_dir: models/texture_reconstruction/
  batch_size: 4096 # 262144 # 20480 # 4096
  learning_rate_mlp: 0.0001 # 0.01 is best until now
  exponential_scheduler_gamma: 1
  # weight_decay_mlp: 0.0001
  weight_decay_mlp: 0
  shuffle_dataloading: True
  loss_type: L1
  render_every: 0
  print_every: 1
  calculate_validation_loss: True
  num_epochs: 1000