  mesh_views_list_train:
    - cat000
    - cat007
    - cat039
    - cat049
    - cat091

  mesh_views_list_val:
    - cat_val000
    - cat_val001
    - cat_val002
    - cat_val003
    - cat_val004
    - cat_val005
    - cat_val006
    - cat_val007
    - cat_val008
    - cat_val009
    - cat_val010
    - cat_val011
    - cat_val012
    - cat_val013
    - cat_val014
    - cat_val015
    - cat_val016
    - cat_val017
    - cat_val018
    - cat_val019
    - cat_val020
    - cat_val021
    - cat_val022
    - cat_val023
    - cat_val024
    - cat_val025
    - cat_val026
    - cat_val027
    - cat_val028
    - cat_val029
    - cat_val030
    - cat_val031
    - cat_val032
    - cat_val033
    - cat_val034
    - cat_val035
    - cat_val036
    - cat_val037
    - cat_val038
    - cat_val039
    - cat_val040
    - cat_val041
    - cat_val042
    - cat_val043
    - cat_val044
    - cat_val045
    - cat_val046
    - cat_val047
    - cat_val048
    - cat_val049
    - cat_val050
    - cat_val051
    - cat_val052
    - cat_val053
    - cat_val054
    - cat_val055
    - cat_val056
    - cat_val057
    - cat_val058
    - cat_val059
    - cat_val060
    - cat_val061
    - cat_val062
    - cat_val063
    - cat_val064
    - cat_val065
    - cat_val066
    - cat_val067
    - cat_val068
    - cat_val069
    - cat_val070
    - cat_val071
    - cat_val072
    - cat_val073
    - cat_val074
    - cat_val075
    - cat_val076
    - cat_val077
    - cat_val078
    - cat_val079
    - cat_val080
    - cat_val081
    - cat_val082
    - cat_val083
    - cat_val084
    - cat_val085
    - cat_val086
    - cat_val087
    - cat_val088
    - cat_val089
    - cat_val090
    - cat_val091
    - cat_val092
    - cat_val093
    - cat_val094
    - cat_val095
    - cat_val096
    - cat_val097
    - cat_val098
    - cat_val099

  # Images which are completely rendered after the evaluation step (not part of the training dataset)
  mesh_views_list_test:
    # - cat_vis004
    - cat_test000
    - cat_test001
    - cat_test002
    - cat_test003
    - cat_test004
    - cat_test005
    - cat_test006
    - cat_test007
    - cat_test008
    - cat_test009
    - cat_test010
    - cat_test011
    - cat_test012
    - cat_test013
    - cat_test014
    - cat_test015
    - cat_test016
    - cat_test017
    - cat_test018
    - cat_test019
    - cat_test020
    - cat_test021
    - cat_test022
    - cat_test023
    - cat_test024
    - cat_test025
    - cat_test026
    - cat_test027
    - cat_test028
    - cat_test029
    - cat_test030
    - cat_test031
    - cat_test032
    - cat_test033
    - cat_test034
    - cat_test035
    - cat_test036
    - cat_test037
    - cat_test038
    - cat_test039
    - cat_test040
    - cat_test041
    - cat_test042
    - cat_test043
    - cat_test044
    - cat_test045
    - cat_test046
    - cat_test047
    - cat_test048
    - cat_test049
    - cat_test050
    - cat_test051
    - cat_test052
    - cat_test053
    - cat_test054
    - cat_test055
    - cat_test056
    - cat_test057
    - cat_test058
    - cat_test059
    - cat_test060
    - cat_test061
    - cat_test062
    - cat_test063
    - cat_test064
    - cat_test065
    - cat_test066
    - cat_test067
    - cat_test068
    - cat_test069
    - cat_test070
    - cat_test071
    - cat_test072
    - cat_test073
    - cat_test074
    - cat_test075
    - cat_test076
    - cat_test077
    - cat_test078
    - cat_test079
    - cat_test080
    - cat_test081
    - cat_test082
    - cat_test083
    - cat_test084
    - cat_test085
    - cat_test086
    - cat_test087
    - cat_test088
    - cat_test089
    - cat_test090
    - cat_test091
    - cat_test092
    - cat_test093
    - cat_test094
    - cat_test095
    - cat_test096
    - cat_test097
    - cat_test098
    - cat_test099
    - cat_test100
    - cat_test101
    - cat_test102
    - cat_test103
    - cat_test104
    - cat_test105
    - cat_test106
    - cat_test107
    - cat_test108
    - cat_test109
    - cat_test110
    - cat_test111
    - cat_test112
    - cat_test113
    - cat_test114
    - cat_test115
    - cat_test116
    - cat_test117
    - cat_test118
    - cat_test119
    - cat_test120
    - cat_test121
    - cat_test122
    - cat_test123
    - cat_test124
    - cat_test125
    - cat_test126
    - cat_test127
    - cat_test128
    - cat_test129
    - cat_test130
    - cat_test131
    - cat_test132
    - cat_test133
    - cat_test134
    - cat_test135
    - cat_test136
    - cat_test137
    - cat_test138
    - cat_test139
    - cat_test140
    - cat_test141
    - cat_test142
    - cat_test143
    - cat_test144
    - cat_test145
    - cat_test146
    - cat_test147
    - cat_test148
    - cat_test149
    - cat_test150
    - cat_test151
    - cat_test152
    - cat_test153
    - cat_test154
    - cat_test155
    - cat_test156
    - cat_test157
    - cat_test158
    - cat_test159
    - cat_test160
    - cat_test161
    - cat_test162
    - cat_test163
    - cat_test164
    - cat_test165
    - cat_test166
    - cat_test167
    - cat_test168
    - cat_test169
    - cat_test170
    - cat_test171
    - cat_test172
    - cat_test173
    - cat_test174
    - cat_test175
    - cat_test176
    - cat_test177
    - cat_test178
    - cat_test179
    - cat_test180
    - cat_test181
    - cat_test182
    - cat_test183
    - cat_test184
    - cat_test185
    - cat_test186
    - cat_test187
    - cat_test188
    - cat_test189
    - cat_test190
    - cat_test191
    - cat_test192
    - cat_test193
    - cat_test194
    - cat_test195
    - cat_test196
    - cat_test197
    - cat_test198
    - cat_test199
