seed: 0
method: neutex
experiment:
  name: Default Neutex
  split: other_method/neutex/cat/default
  description: Default Config for cat using neutex method
data:
  raw_data_path: data/raw/cat_dataset_v2_tiny/
  train_render_img_names:
    - cat_vis000
    - cat000
    - cat_val000
    - cat_test000

  render_img_directory: results_texture/

  preproc_data_path: data/preprocessed/cat_dataset_v2_tiny/
  eigenfunctions_path: data/preprocessed/cat_efuncs/eigenfunctions_cotan_kmax4096_skip_first_efuncs.npy
  mesh_path: data/raw/cat_rescaled_rotated/12221_Cat_v1_l3.obj
  img_height: 512
  img_width: 512
  data_split: config/texture/cat/data_split.yaml
  
  # Images which are completely rendered after the evaluation step (not part of the training dataset)
  eval_render_input_paths:
      - data/cat_dataset_v2_tiny/cat_vis000
      - data/cat_dataset_v2_tiny/cat_vis001
      - data/cat_dataset_v2_tiny/cat_vis002
      - data/cat_dataset_v2_tiny/cat_vis003
      - data/cat_dataset_v2_tiny/cat_vis004
  eval_render_img_names:
      - cat_vis000
      - cat_vis001
      - cat_vis002
      - cat_vis003
      - cat_vis004
model:
  type: neutex
  feature_strategy: xyz
  pretrained_path: src/other_methods/neutex/pretrained/cat_rescaled_rotated_pretrained_neutex_mapping.pt
  # Linspace with embedding size for positional encoding => 170 * 2 * 3 + 3 = 1023
  k: 170
  use_logspace: False
  max_freq: 6
training:
  out_dir: models/texture_reconstruction/
  batch_size: 4096 # 262144 # 20480 # 4096
  learning_rate_mlp: 0.0001 # 0.01 is best until now
  exponential_scheduler_gamma: 1
  # weight_decay_mlp: 0.0001
  weight_decay_mlp: 0
  shuffle_dataloading: True
  loss_type: L1
  render_every: 0
  print_every: 1
  calculate_validation_loss: True
  num_epochs: 1000
